"""empty message

Revision ID: 8ff643d7409d
Revises: 1dc37ddfd7d9
Create Date: 2021-05-27 20:45:11.673270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff643d7409d'
down_revision = '1dc37ddfd7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=6),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=5),
               nullable=True)
    # ### end Alembic commands ###
